#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 101pong.py
## File description:
## a program to mimic Pong
##

import sys
import math

li = ((float(sys.argv[4]) - float(sys.argv[1])), (float(sys.argv[5]) - float(sys.argv[2])), (float(sys.argv[6]) - float(sys.argv[3])))
print("The velocity vector of the ball is:")
print("(%.2f,  %.2f, %.2f)" % (li[0], li[1], li[2]))
print("At time t + " + sys.argv[7] + ", ball coordinates will be:")
li2 = ((float(sys.argv[4]) + (li[0] * float(sys.argv[7])), float(sys.argv[5]) + (li[1] * float(sys.argv[7])), float(sys.argv[6]) + (li[2] * float(sys.argv[7]))))
print("(%.2f,  %.2f, %.2f)" % (li2[0], li2[1], li2[2]))
if (float(sys.argv[6]) < 0) and (li2[2] < 0) or (float(sys.argv[6]) > 0) and (li2[2] > 0) :
    print("The ball won’t reach the paddle.")
else :
    norm = (math.sqrt((li2[0] ** 2) + (li2[1] ** 2) + (li2[2] ** 2)))
    print("norm = %d z = %d", norm, sys.argv[6])
    res = (math.asin(float(sys.argv[6]) / norm) * (180/math.pi))
    print("The incidence angle is:")
    print("%.2f degrees" % res)