#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 101pong.py
## File description:
## a program to mimic Pong
##

import sys
import math

i = 1
while (i < len(sys.argv)):
    try:
        int(sys.argv[i])
    except:
        sys.exit(84)
    i += 1
if (len(sys.argv) != 8 or float(sys.argv[7]) < 0 or float(sys.argv[7]) != int(math.ceil(float(sys.argv[7])))):
    sys.exit(84)
li = ((float(sys.argv[4]) - float(sys.argv[1])), (float(sys.argv[5]) - float(sys.argv[2])), (float(sys.argv[6]) - float(sys.argv[3])))
print("The velocity vector of the ball is:")
print("(%.2f,  %.2f, %.2f)" % (li[0], li[1], li[2]))
print("At time t + " + sys.argv[7] + ", ball coordinates will be:")
li2 = ((float(sys.argv[4]) + (li[0] * float(sys.argv[7])), float(sys.argv[5]) + (li[1] * float(sys.argv[7])), float(sys.argv[6]) + (li[2] * float(sys.argv[7]))))
print("(%.2f,  %.2f, %.2f)" % (li2[0], li2[1], li2[2]))
if (float(sys.argv[6]) < 0) and (li2[2] < 0) or (float(sys.argv[6]) > 0) and (li2[2] > 0) :
    print("The ball won't reach the paddle.")
else :
    norm = (math.sqrt((li[0] ** 2) + (li[1] ** 2) + (li[2] ** 2)))
    res = ((math.asin(float(math.sqrt(li[2] ** 2)) / norm)) * (180/math.pi))
    print("The incidence angle is:")
    print("%.2f degrees" % res)
